#pragma once

#include <vector>
#include <string>

namespace staticdata {

	struct country_t {
		std::string code;
		std::string name;
	};

	std::vector<country_t> countries = {
		{"ABW","Aruba"},
		{"AFG","Afghanistan"},
		{"AFS","South Africa"},
		{"AGL","Angola"},
		{"AIA","Anguilla"},
		{"ALB","Albania"},
		{"ALG","Algeria"},
		{"ALS","Alaska"},
		{"AMS","Saint Pauland Amsterdam Islands"},
		{"AND","Andorra"},
		{"AOE","Western Sahara"},
		{"ARG","Argentina"},
		{"ARM","Armenia"},
		{"ARS","Saudi Arabia"},
		{"ASC","Ascension Island"},
		{"ATA","Antarctic"},
		{"ATG","Antigua and Barbuda"},
		{"ATN","Netherlands Antilles"},
		{"AUS","Australia"},
		{"AUT","Austria"},
		{"AZE","Azerbaijan"},
		{"AZR","Azores"},
		{"B","Brazil"},
		{"BAH","Bahamas"},
		{"BDI","Burundi"},
		{"BEL","Belgium"},
		{"BEN","Benin"},
		{"BER","Bermuda"},
		{"BFA","Burkina Faso"},
		{"BGD","Bangladesh"},
		{"BHR","Bahrain"},
		{"BIH","Bosnia and Herzegovina"},
		{"BIO","Chagos Islands"},
		{"BLR","Belarus"},
		{"BLZ","Belize"},
		{"BOL","Bolivia"},
		{"BOT","Botswana"},
		{"BRB","Barbados"},
		{"BRM","Myanmar"},
		{"BRU","Brunei Darussalam"},
		{"BTN","Bhutan"},
		{"BUL","Bulgaria"},
		{"BVT","Bouvet Island"},
		{"CAF","Central African Rep."},
		{"CAN","Canada"},
		{"CBG","Cambodia"},
		{"CG7","Guantanamo"},
		{"CHL","Chile"},
		{"CHN","China"},
		{"CHR","Christmas Island"},
		{"CKH","Cook Islands"},
		{"CLM","Colombia"},
		{"CLN","Sri Lanka"},
		{"CME","Cameroon"},
		{"CNR","Canary Islands"},
		{"COD","Dem. Rep. of the Congo"},
		{"COG","Congo (Rep. of the)"},
		{"COM","Comoros"},
		{"CPT","Clipperton Island"},
		{"CPV","Cabo Verde"},
		{"CRO","Crozet Archipelago"},
		{"CTI","C?te d'Ivoire"},
		{"CTR","Costa Rica"},
		{"CUB","Cuba"},
		{"CVA","Vatican"},
		{"CYM","Cayman Islands"},
		{"CYP","Cyprus"},
		{"CZE","Czech Republic"},
		{"D","Germany"},
		{"DGA","Diego Garcia"},
		{"DJI","Djibouti"},
		{"DMA","Dominica"},
		{"DNK","Denmark"},
		{"DOM","Dominican Rep."},
		{"E","Spain"},
		{"EGY","Egypt"},
		{"EQA","Ecuador"},
		{"ERI","Eritrea"},
		{"EST","Estonia"},
		{"ETH","Ethiopia"},
		{"F","France"},
		{"FIN","Finland"},
		{"FJI","Fiji"},
		{"FLK","Falkland Islands"},
		{"FRO","Faroe Islands"},
		{"FSM","Micronesia"},
		{"G","United Kingdom"},
		{"GAB","Gabon"},
		{"GCA","United Kingdom Region 1"},
		{"GCC","United Kingdom Region 3"},
		{"GDL","Guadeloupe"},
		{"GEO","Georgia"},
		{"GHA","Ghana"},
		{"GIB","Gibraltar"},
		{"GMB","Gambia"},
		{"GNB","Guinea-Bissau"},
		{"GNE","Equatorial Guinea"},
		{"GRC","Greece"},
		{"GRD","Grenada"},
		{"GRL","Greenland"},
		{"GTM","Guatemala"},
		{"GUF","Guiana"},
		{"GUI","Guinea"},
		{"GUM","Guam"},
		{"GUY","Guyana"},
		{"HKG","Hong Kong"},
		{"HMD","Heard and McDonald Islands"},
		{"HND","Honduras"},
		{"HNG","Hungary"},
		{"HOL","Netherlands"},
		{"HRV","Croatia"},
		{"HTI","Haiti"},
		{"HWA","Hawaii"},
		{"HWL","Howland Island"},
		{"I","Italy"},
		{"ICO","Cocos (Keeling) Islands"},
		{"IND","India"},
		{"INS","Indonesia"},
		{"IRL","Ireland"},
		{"IRN","Iran"},
		{"IRQ","Iraq"},
		{"ISL","Iceland"},
		{"ISR","Israel"},
		{"J","Japan"},
		{"JAR","Jarvis Island"},
		{"JMC","Jamaica"},
		{"JON","Johnston Island"},
		{"JOR","Jordan"},
		{"KAZ","Kazakhstan"},
		{"KEN","Kenya"},
		{"KER","Kerguelen Islands"},
		{"KGZ","Kyrgyzstan"},
		{"KIR","Kiribati"},
		{"KNA","Saint Kitts and Nevis"},
		{"KOR","Korea"},
		{"KRE","Dem. People's Rep. of Korea"},
		{"KWT","Kuwait"},
		{"LAO","Lao P.D.R."},
		{"LBN","Lebanon"},
		{"LBR","Liberia"},
		{"LBY","Libya"},
		{"LCA","Saint Lucia"},
		{"LIE","Liechtenstein"},
		{"LSO","Lesotho"},
		{"LTU","Lithuania"},
		{"LUX","Luxembourg"},
		{"LVA","Latvia"},
		{"MAC","Macau"},
		{"MAU","Mauritius"},
		{"MCO","Monaco"},
		{"MDA","Moldova"},
		{"MDG","Madagascar"},
		{"MDR","Madeira"},
		{"MDW","Midway Islands"},
		{"MEX","Mexico"},
		{"MHL","Marshall Islands"},
		{"MKD","North Macedonia"},
		{"MLA","Malaysia"},
		{"MLD","Maldives"},
		{"MLI","Mali"},
		{"MLT","Malta"},
		{"MNE","Montenegro"},
		{"MNG","Mongolia"},
		{"MOZ","Mozambique"},
		{"MRA","Northern Mariana Islands"},
		{"MRC","Morocco"},
		{"MRN","Marion Island"},
		{"MRT","Martinique"},
		{"MSR","Montserrat"},
		{"MTN","Mauritania"},
		{"MWI","Malawi"},
		{"MYT","Mayotte"},
		{"NCG","Nicaragua"},
		{"NCL","New Caledonia"},
		{"NFK","Norfolk Island"},
		{"NGR","Niger"},
		{"NIG","Nigeria"},
		{"NIU","Niue"},
		{"NMB","Namibia"},
		{"NOR","Norway"},
		{"NPL","Nepal"},
		{"NRU","Nauru"},
		{"NZL","New Zealand"},
		{"OCE","French Polynesia"},
		{"OMA","Oman"},
		{"PAK","Pakistan"},
		{"PAQ","Easter Island"},
		{"PHL","Philippines"},
		{"PHX","Phoenix Islands"},
		{"PLM","Palmyra Island"},
		{"PLW","Palau"},
		{"PNG","Papua New Guinea"},
		{"PNR","Panama"},
		{"POL","Poland"},
		{"POR","Portugal"},
		{"PRG","Paraguay"},
		{"PRU","Peru"},
		{"PTC","Pitcairn Island"},
		{"PTR","Puerto Rico"},
		{"QAT","Qatar"},
		{"REU","Reunion"},
		{"RKS","Kosovo"},
		{"ROD","Rodrigues"},
		{"ROU","Romania"},
		{"RRW","Rwanda"},
		{"RUS","Russian Federation"},
		{"S","Sweden"},
		{"SCG","ex Serbia and Montenegro? SRB, MNE"},
		{"SDN","Sudan"},
		{"SEN","Senegal"},
		{"SEY","Seychelles"},
		{"SHN","Saint Helena"},
		{"SLM","Solomon Islands"},
		{"SLV","El Salvador"},
		{"SMA","American Samoa"},
		{"SMO","Samoa"},
		{"SMR","San Marino"},
		{"SNG","Singapore"},
		{"SOM","Somalia"},
		{"SPM","Saint Pierre and Miquelon"},
		{"SRB","Serbia"},
		{"SRL","Sierra Leone"},
		{"SSD","South Sudan"},
		{"STP","Sao Tome and Principe"},
		{"SUI","Switzerland"},
		{"SUR","Suriname"},
		{"SVK","Slovakia"},
		{"SVN","Slovenia"},
		{"SWN","Swan Islands"},
		{"SWZ","Eswatini"},
		{"SYR","Syrian Arab Republic"},
		{"TCA","Turks and Caicos Islands"},
		{"TCD","Chad"},
		{"TGO","Togo"},
		{"THA","Thailand"},
		{"TJK","Tajikistan"},
		{"TKL","Tokelau"},
		{"TKM","Turkmenistan"},
		{"TLS","Timor-Leste"},
		{"TON","Tonga"},
		{"TRC","Tristan da Cunha"},
		{"TRD","Trinidad and Tobago"},
		{"TUN","Tunisia"},
		{"TUR","Turkey"},
		{"TUV","Tuvalu"},
		{"TZA","Tanzania"},
		{"UAE","United Arab Emirates"},
		{"UGA","Uganda"},
		{"UKR","Ukraine"},
		{"URG","Uruguay"},
		{"USA","United States"},
		{"UZB","Uzbekistan"},
		{"VCT","Saint Vincent and the Grenadines"},
		{"VEN","Venezuela"},
		{"VIR","United States Virgin Islands"},
		{"VRG","British Virgin Islands"},
		{"VTN","Viet Nam"},
		{"VUT","Vanuatu"},
		{"WAK","Wake Island"},
		{"WAL","Wallis and Futuna Islands"},
		{"XAA","Shared throughout the world"},
		{"XAX","Shared by several countries"},
		{"XBR","Special use"},
		{"XBY","Abyeiarea"},
		{"XCQ","ex Caroline Islands"},
		{"XCS","ex Czechoslovakia"},
		{"XGZ","Gaza Strip"},
		{"XMM","Inter-ship communications"},
		{"XOA","International Civil Aviation Organization"},
		{"XR1","Region 1"},
		{"XR2","Region 2"},
		{"XR3","Region 3"},
		{"XRY","Antarctic Region"},
		{"XSC","ex Serbia and Montenegro"},
		{"XSD","ex Republic of the Sudan"},
		{"XSP","Spratly Islands"},
		{"XSU","ex Soviet Union"},
		{"XUN","United Nations"},
		{"XWB","West Bank"},
		{"XWM","World Meteorological Organization"},
		{"XYU","ex Yugoslavia"},
		{"YEM","Yemen"},
		{"ZMB","Zambia"},
		{"ZWE","Zimbabwe"}
	};
}